# Generated by Django 3.0.4 on 2020-03-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Booking'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Route'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Route'),
        ),
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Booking'),
        ),
        migrations.AddField(
            model_name='route',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Booking'),
        ),
    ]
