# Generated by Django 3.0.4 on 2020-03-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtc', '0002_auto_20200323_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='route',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='bus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Route'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Route'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtc.Booking'),
        ),
    ]
